FROM debian:10.10

MAINTAINER phomburg@ripe.net

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y autoconf
RUN apt-get install -y libtool
RUN apt-get install -y make
RUN apt-get install -y libssl-dev
RUN apt-get install -y fakeroot
