FROM debian:12.0

MAINTAINER mstam@ripe.net

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y libssl-dev
RUN apt-get install -y build-essential
RUN apt-get install -y autoconf
RUN apt-get install -y debhelper
RUN apt-get install -y gpg
RUN apt-get install -y lsb-release
