#!/bin/sh

test()
{
	opt="$1"
	target="$2"
	name="$3"

	filebase=testsuite/evntp-data/"evntp-$name"
	output="$filebase".out
	packets="$filebase".net
	rm -f "$output" "$packets"
	ATLAS_TESTS=yes ATLAS_UNSAFE=yes ./busybox evntp $opt -O "$output" -W "$packets" "$target"
}

test "-6" "ntp.ripe.net" "6"
test "-4" "ntp.ripe.net" "4"
test "-6 -c1" "ntp.ripe.net" "c1"
test "-6 -A42" "ntp.ripe.net" "A42"
test "-6 -A42 -B43" "ntp.ripe.net" "B43"
